Repository Community-VyProjects/VyManager, pull requests merged in 2025-04, with the labels that each got.

#30 Improve displaying API errors from CLI commands
  frontend/app/advanced/page.tsx
  frontend/app/firewall/page.tsx
  frontend/app/interfaces/page.tsx
Labels: enhancement

#34 backend: Feature#33 - Add GraphQL API
  client.py
  endpoints/graphql.py
Labels: documentation, enhancement, help wanted, python

#42 routing: bug#41: fix routing table 1.5
  main.py
Labels: bug

#45 routing: feature#44: add vrf support to routing page
  frontend/app/routing/page.tsx
  main.py
Labels: enhancement

#40 Saving methods for changing configurations (issue #39)
  frontend/app/containers/page.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/firewall/groups/page.tsx
  frontend/app/firewall/page.tsx
  frontend/app/interfaces/page.tsx
  frontend/app/nat/page.tsx
  frontend/app/page.tsx
  frontend/app/routing/page.tsx
  frontend/app/services/dhcp/page.tsx
  frontend/app/services/https/page.tsx
  frontend/app/services/ntp/page.tsx
  frontend/app/services/page.tsx
  frontend/app/services/ssh/page.tsx
  frontend/app/system/page.tsx
  frontend/app/utils.tsx
  frontend/app/vpn/page.tsx
  main.py
Labels: bug, good first issue, python

#50 routing: Bug#49: Fix VRF multiple prefix in 1.4
  main.py
Labels: bug

#52 Improve merge_cidr_parts security
  utils.py
Labels: python, security

#55 graphql: Feature#54: Add GraphQL keys to the API
  endpoints/graphql.py
Labels: enhancement

#59 feature: Add system performance option
  frontend/app/system/page.tsx
Labels: enhancement

#60 Add saving method warning
  frontend/app/system/page.tsx
Labels: enhancement
